### ISSUE TITLE
Extreme CPU usage by the function findAndConnectToBoard()

### ISSUE THREAD

**Issue by Finnadip** [OSRTT/OSLTT#3]
Describe the bug
3 Billion Cycles - same as updatelog()

To Reproduce

1. Launch the program
2. View cpu cycle usage in process explorer

Expected behavior
No excess usage of cpu cycles

Additional context
Caused by findAndConnectToBoard() constantly looping unnecessarily

**Comment by andymanic** [comment]
I wanted to update this as I had a brief look last night after finally getting Visual Studio's performance logger working again. The same code in the OSRTT software is functionally 0% CPU usage, but in OSLTT it's insane. Happily I found the problem and I'll have this one fixed in the next update - it drops CPU usage by 10% on my system. I'll close this once the update is live.
